export const foods = [
  {
    id: "sandwich",
    name: "Sandwich 🥪",
    price: 10,
    hunger: 20,
    description: "Un bon sandwich pour reprendre des forces.",
  },
  {
    id: "pizza",
    name: "Pizza 🍕",
    price: 25,
    hunger: 50,
    hapiness: 10,
    hygiene: -5,
    thirst: -5,
    description: "Un repas copieux qui rassasie bien.",
  },
  {
    id: "gateau",
    name: "Gâteau 🍰",
    price: 15,
    hunger: 10,
    hapiness: 5,
    hygiene: -2,
    description: "Un petit plaisir sucré.",
  },
  {
    id: "eau",
    name: "Eau 💧",
    price: 15,
    hunger: 10,
    description: "Une boisson essentielle pour rester hydraté.",
  },
  {
    id: "cafe",
    name: "Café ☕",
    price: 15,
    hunger: 0,
    thirst: 5,
    energy: 20,
    stress: 5,
    description: "Un café pour rester éveillé et concentré.",
  },
];
